cyverse/clank

- ratchet.py
- ratchet_requirements.txt
modified:   ratchet.py
modified:   ratchet_requirements.txt
I have no idea where else to place `init(autoreset=True)` on line 13. Any ideas are welcome.
> Replace ascii color printing with colorama

- roles/clone-repo/tasks/main.yml
Canonical way of creating a directory. Removes Ansible warning.
> Simplified creating repo base directory

- playbooks/setup_troposphere.yml
modified:   setup_troposphere.yml
Add role task to logrotate troposphere logs.
> Add troposphere logrotate file

- roles/logrotate-files/tasks/main.yml
> Change logrotate file permissions to 644

- playbooks/utils/perform_backups.yml
- roles/app-backup-postgres/README.md
- roles/app-backup-postgres/defaults/main.yml
- roles/app-backup-postgres/tasks/main.yml
Using the role that @lenards created with a few changes, I created a simple playbook to perform automated backups in hopes that deploys go slightly faster.
> Simple playbook to perform backups on our database.

- .travis.yml
Perform a purge of redis-server, before clank add the chris-lea redis-server ppa. This appears to work. Also, dropped the postregsql version back to 9.5.
> Fix redis-server issue on travis

- playbooks/utils/upgrade_postgres.yml
modified:   playbooks/utils/upgrade_postgres.yml
> Variablize postgres version number

- README.md
- clank.py
> Extra ansible playbook args

- dist_files/variables.yml.dist
@julianpistorius @lenards Am I close?
> Documenting web desktop variables for the deployer's benefit

- dist_files/variables.yml.dist
To be merged after https://github.com/cyverse/atmosphere/pull/237 this will guide users on how to use the new feature.
> Changes to the variables.yml.dist

- README.md
- dist_files/variables.yml.dist
1. add `pip install virtualenv` in the readme
2. change the repo location of atmosphere-ansible 
Please let me know if you have any question. Thanks! 
Lucas
> Edit ReadMe and change the repo location for atmosphere-ansible 

- group_vars/atmosphere
- group_vars/troposphere
Configuration available for both atmosphere and troposphere
Changes to Atmosphere & Troposphere --
https://github.com/cyverse/troposphere/pull/559
https://github.com/cyverse/atmosphere/pull/289
Changes to the variables.yml --
https://gitlab.cyverse.org/atmosphere/atmo-prod/merge_requests/9
https://gitlab.cyverse.org/atmosphere/atmo-beta/merge_requests/10
> Include SENTRY as a configurable

- roles/tls-cert/README.md
- roles/tls-cert/meta/.galaxy_install_info
- roles/tls-cert/tasks/deploy-provided.yml
Problem: The existing solution is too complex and doesn't work!
Solution: Revert old solution, and opt for simpler solution that just recreates full chain every time
This pr undoes the changes here -> https://github.com/cyverse/clank/pull/172. And applies a simpler fix.
From aea5785:
> After talking with @c-mart, it became apparent that this was an interesting
solution but overkill. I'm reverting it rather than nuking it, because it is
already published in several places and because it may be useful to refer to
at some point in the future where the complexity is warranted.
> Submit simpler fix for full chain bug

- HACKING.md
- README.md
Here is some documentation that may be useful to others. It's just a oneline command to run any role in clank without setting up vars and hosts.
> Add hacking doc

- group_vars/atmosphere
- group_vars/troposphere
- roles/clone-repo/defaults/main.yml
- roles/clone-repo/tasks/main.yml
This PR will be used to support [Atmosphere](https://github.com/cyverse/atmosphere/pull/357) and [Troposphere](https://github.com/cyverse/troposphere/pull/611) PRs.
> Web Token Support

- group_vars/atmosphere
- group_vars/troposphere
This allows the "project sharing" feature to be toggled on/off.
> Problem: ENABLE_PROJECT_SHARING missing group_vars

- CHANGELOG.md
- dist_files/variables.yml.dist
- group_vars/common
Solution: Default `INSTALLATION_TYPE: "production"`
> Problem: Too easy to run prod in dev mode

- .gitignore
- group_vars/atmosphere
Solution:
- Disable libcloud logging by default
- Include documentation to explain what the setting does.
> Problem: libcloud logging is enabled by default

- PULL_REQUEST_TEMPLATE.md
> Include PR template

- group_vars/atmosphere
- group_vars/troposphere
Solution: Use `LOCAL_DEV: True` variable to enable uWSGI
`python-autoreload` feature.
> Problem: Manual uWSGI reload in dev environment - Nope

- group_vars/atmosphere
required for atmosphere/503
WIP until 503 is :shipit:
> Include new variables: `ALLOCATION_SOURCE_COMPUTE_ALLOWED`, `AUTO_CREATE_NEW_PROJECTS` 

- roles/app-django-manage-load-tables/defaults/main.yml
> Include 'pattern_match.json' as a fixture to be added

- dist_files/atmosphere-ansible/group_vars/atmosphere-provider1
- dist_files/atmosphere-ansible/group_vars/atmosphere-provider2
- dist_files/atmosphere-ansible/hosts.yml.dist
- Include hosts file for bootstrapping atmosphere-ansible
- Include group_vars file(s) for bootstrapping atmosphere-ansible
> Re-add distfiles for atmosphere-ansible

- dist_files/variables.yml.dist
- group_vars/atmosphere
Please describe your pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue. When linking to an issue, please use
`refs #...` in the description of the pull request.
Include snippets of code to help reviewers test your code!
> Include MachineValidationPlugin support for atmosphere

- group_vars/atmosphere
required for companion PR: https://github.com/cyverse/atmosphere/pull/538
- (Do we want to disable this for prod systems? I wouldn't mind it being enabled on all repos..)
> Include 'ENABLE_DEV_ENDPOINT' in atmosphere/group_vars

- group_vars/atmosphere
- roles/install-dependencies/vars/Ubuntu.yml
Issues found during v29 mock release
> Fix errors found during mock release of v29

- dist_files/variables.yml.dist
> Document SERVER_NAME variable

- roles/setup-celery/tasks/main.yml
- roles/setup-celery/templates/flower.conf
Include flower in nginx locations
> Problem: Clank installs flower, but flower is missing from /etc/nginx/locations

- playbooks/setup_atmosphere.yml
I got a yaml parse error while running on atmo-local caused by this missing comma.
> Fix yaml parse error caused by missing comma

- CHANGELOG.md
- dist_files/variables.yml.dist
- group_vars/atmosphere
- group_vars/troposphere
Remove the vars for the refactors in:
https://github.com/cyverse/atmosphere/pull/665
https://github.com/cyverse/troposphere/pull/793
> Cleanup email variables ATMO-2169
