roles/install-dependencies/vars/Ubuntu.yml
As notes [here](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), the `build-essential` debian packages needs to be present to build native dependencies. An example of this within troposphere's `package.json` would be `node-sass`. 
This is currently working on the dev build server because this package is **already** present.
=> Added `build-essential` package needed for compiling native _node_ packages.

roles/troposphere-setup-troposphere/tasks/main.yml
For now, we will force builds & deployments to install all dependencies.
Choosing between `requirements.txt` & `dev_requirements.txt` would be an
enhancements for the over tool. This would likely be controlled by the master
`variables.yml` file (or a more Ansible-like approach).
**Note:** this only _affects_ the `deploy_troposphere` playbook's task.
=> Change `pip install` module to use dev requirements for troposphere

roles/troposphere-setup-troposphere/tasks/main.yml
With assistance from Matt Deporter, we triaged the problem of "stale" playbook/role execution on the build server. It appeared that the `state=latest` needed to be added to the role using the `pip` module. Adding this provided as successful run within a clean, isolated workspace directory.
=> Change the `pip` module to request latest as `state`.

roles/atmosphere-clone-repo/tasks/main.yml, roles/troposphere-clone-repo/tasks/main.yml
This used the assumption that a git repository *has* to have a `.git` to be valid. So here, we just tack it onto the location used within `stat` module. 
**Refactor note:** - it looks like all pulling/cloning _roles_ could be factored out from the "troposphere-*-repo", "atmosphere-*-repo", & "atmo-ansible-*-repo" into generalized tasks.
=> Changed repo check to use `.git` to ensure a repo is present.

roles/install-dependencies/vars/Ubuntu.yml
The block of packages under `APACHE_PACKAGES` is never used within the `install-dependencies` role. Remove, as unused. 
_Also..._
Neither atmosphere nor troposphere will be actively supported by the team running in a configuration with _apache2 + mod_wsgi_ given previous issue encountered while using apache in production. We offer a Python source-level notion that running the application with _such_ a configuration is *possible* but not one we will actively support. As such, we should begin removing apache configurations from clank, atmosphere, & troposphere repositories. 
This is per approval from @steve-gregory. If I have misunderstood, we can definitely close this PR.
=> Remove apache2 from install dependency consideration.

ratchet.py
Currently, the ratchet.py `main()` has two unhandle sources for errors: 
- `prepare_ansible_cfg`
- `prepare_ansible_env_file`
This pull request would push along the exit codes returned by `install_dependencies` & `execute_ansible_playbook`.  
It also proposes that a general `sys.exit(1)` should be included as the last line in the `except`: 
```python
try:
install_dependencies(args)
prepare_ansible_cfg(args)
prepare_ansible_env_file(args)
execute_ansible_playbook(args)
except Exception as exc:
print "Error executing Ratchet: %s" % exc.message
parser.print_help()
traceback.print_exc(file=sys.stdout)
```
So, the outline for `main()`: 
```python
try:
install_dependencies(args)
prepare_ansible_cfg(args)
prepare_ansible_env_file(args)
execute_ansible_playbook(args)
except Exception as exc: …
```
=> Pass along exit code from subprocess; exit(1) on exception.

roles/atmosphere-setup-atmosphere/tasks/main.yml, roles/atmosphere-setup-atmosphere/templates/atmo_bash_aliases.j2, roles/troposphere-setup-troposphere/tasks/main.yml, roles/troposphere-setup-troposphere/templates/tropo_bash_aliases.j2
Added a simple feature to ensure that the new Ansible 2.0 were available to us.
=> Add bash aliases for atmo and tropo to test new Ansible 2.0 modules

dist_files/variables.yml.dist, playbooks/deploy_atmosphere.yml, playbooks/setup_atmosphere.yml, roles/app-install-instance-deploy-automation/tasks/main.yml, roles/app-install-instance-deploy-automation/templates/ssh_config.j2, roles/app-setup-ssh-keys/tasks/main.yml, roles/app-setup-ssh-keys/templates/ssh_config.j2, roles/app-setup-ssh-keys/vars/main.yml, roles/setup-ssl/tasks/main.yml, roles/setup-ssl/vars/CentOS.yml, roles/setup-ssl/vars/Ubuntu.yml, roles/setup-ssl/vars/default.yml, roles/setup-ssl/vars/main.yml
A bit of a large commit.
I wanted to make ssl cert and ssh key creation the default. This will help simplify the process of a new atmosphere/troposphere install for a user/team who just wants to deploy this with minimal effort as possible. I will update our versioned variable.yml files to account for this change assuming the PR has been accepted. 
I created a small ssh key role to help keep things organized and slimmed down the vars files in the `setup-ssl` roles.
Finally, I added in the clone atmosphere-ansible task/role as it was missing from the large rewrite. It uses the general clone-repo that @lenards wrote, rather than adding it as a task elsewhere. 
What I want to have a discussion on is whether we should have atmosphere perform a configure run as Steve wrote in his PR, or should …
=> Make ssl certs and ssh key creation the default

roles/config-nginx-uwsgi/tasks/main.yml, roles/setup-celery/tasks/main.yml
Added a tag to task that should be ran on deployments only.
To use tag for jenkins builds, be sure to add `--skip-tags deploy` to use this feature.
We are still replacing celeryd on the jenkins install.. - @steve-gregory 
`lrwxrwxrwx 1 root root 94 May  4 20:47 /etc/default/celeryd -> /var/lib/jenkins/jobs/Build_Test_Atmosphere/workspace/atmosphere/extras/init.d/celeryd.default`
`atmosphere.ini -> /var/lib/jenkins/jobs/Build_Test_Atmosphere/workspace/atmosphere/extras/uwsgi/atmo.uwsgi.ini
`
=> Prevent bulldozing of jenkins builds over deploys

playbooks/deploy_atmosphere.yml, playbooks/setup_atmosphere.yml, roles/app-pip-install-requirements/tasks/main.yml, roles/app-pip-install-requirements/vars/main.yml, roles/logrotate-files/README.md, roles/logrotate-files/defaults/main.yml, roles/logrotate-files/tasks/main.yml
I created logrotate role to allow atmosphere and celery logs to be rotated. The role is generic and can be used by passing in a single file or a list or files to be linked (at the recommendation of Andy Edmonds).
This commit is to address github [issue](https://github.com/iPlantCollaborativeOpenSource/clank/issues/46).
Documentation has been prepared and the role has been tested.
=> Add logrotate role

roles/install-dependencies/tasks/main.yml
Currently, Clank adds `'ppa:chris-lea/node.js'` and then installs the `nodejs` package from there. This repository is frozen as 0.10.37 (prior to the iojs + nodejs projects {re}merging).
Chris Lea's repository is the basis for [NodeSource](https://nodesource.com/) distribution. So, the current approach for installing from NodeSource is something like: 
```bash
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
```
source: [nodejs.org/](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)
What this pull request does is: 
- remove `chris-lea/node.js` ppa if present
- add the NodeSource gpg key
- add the NodeSource repository
- install nodejs (4.x) from NodeSource\*\*
✅ Verified within vagrant environment via …
=> Handle `nodejs` repository update

roles/install-dependencies/tasks/main.yml, roles/install-dependencies/vars/Ubuntu.yml
This gives Ubuntu Trusty (14.04) access to a most recent nginx version.
We are also opting for the `nginx-full` package here. A call to `nginx -V` will give you a complete listing of all modules present following the install. 
The LTS has nginx 1.4.6 as the stock, available package. Including the stable ppa from the Nginx team will give us access to nginx 1.10.*
This means the HTTP/2 module can be enable to increase the delivery throughput of assets (images, style, typography, javascript).
See [ATMO-1372](https://pods.iplantcollaborative.org/jira/browse/ATMO-1372)
Relates to [ATMO-1189](https://pods.iplantcollaborative.org/jira/browse/ATMO-1189)
=> Add Nginx team ppa repo for stable, current version

playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml, roles/delete-files/README.md, roles/delete-files/defaults/main.yml, roles/delete-files/tasks/main.yml
This is to address issue [55](https://github.com/iPlantCollaborativeOpenSource/clank/issues/55). This role is generic and can accept a location to recursively search down and matching a file glob that is provided. Then nuke it. It as has been added to the setup_atmosphere.yml playbook so we should be able to remove that issue going forward.
=> Remove pycs

dist_files/variables.yml.dist, roles/app-setup-ssh-keys/tasks/main.yml, roles/app-setup-ssh-keys/templates/ssh_config.j2, roles/app-setup-ssh-keys/vars/main.yml
In an effort to remove the bug of blockinfile not properly capturing the Host * directive, I decided to template out the .ssh/config file. This works well, has a comment at the top stating that it is being managed by ansible, and points to the private ssh key that is injected by ansible in the config with proper naming. 
If you do not wish to have to ansible write over the ssh config that may be in place, you can set `GENERATE_SSH_CONFIG` to `false` and it will skip over this task.
This should address issue [56](https://github.com/iPlantCollaborativeOpenSource/clank/issues/56).
=> Template ssh config and set var to false if user doesn't want it to be generated

roles/install-dependencies/tasks/main.yml, roles/install-dependencies/vars/Ubuntu.yml
This PR is to address the issue brought up in [53](https://github.com/iPlantCollaborativeOpenSource/clank/issues/53) and what @nfaction was trying to explain in issue [51](https://github.com/iPlantCollaborativeOpenSource/clank/pull/51). The code removes multiple unnecessary tasks and creates three lists that can easily be appended to if we wish to add any apt repos/keys going forward. The code has been tested.
=> Condense apt-keys and apt-repos into lists that can easily be added onto

roles/build-install-troposphere-ui-assets/tasks/main.yml
This PR is to address issue [54](https://github.com/iPlantCollaborativeOpenSource/clank/issues/54). 
We first run `npm set progress=false` to help increase npm install build times. You can see this [article](https://davidwalsh.name/faster-npm) for more info about this. 
Next we run an initial `npm install` and record its results. If it fails, we delete `node_modules` and re run the install again (try twice for any funky npm voodoo). 
There is a slight speed increase and is noted below:
```
/root/clank/clank_env/bin/ansible-playbook /root/clank/playbooks/deploy_stack.yml --flush-cache -c local -i "/root/clank/local_inventory" --skip-tags="dependencies,atmosphere" -e "@/root/clank/variables.yml@atmo"
real    2m56.866s
user    2m21.271s
sys     0m29.787s …
```
=> Remove node_modules when npm install fails and launches second attempt

ansible.cfg.j2, callback_plugins/human_log.py
After an embarrassing meeting and having trouble reading output from the configure script, I have added a callback plugin that will make spit the output as intended.
Takes this:
```
TASK [app-generate-ini-config : run generate script for app] *******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/opt/env/troposphere/bin/python /opt/dev/troposphere/configure", "delta": "0:00:00.166891", "end": "2016-06-27 11:59:02.153102", "failed": true, "rc": 1, "start": "2016-06-27 11:59:01.986211", "stderr": "", "stdout": "\u001b[30m\u001b[46m\nProject Path => /opt/dev/troposphere\u001b[0m\n\n\nTesting for preconditions...\n\n\u001b[31mError found in /opt/dev/troposphere/troposphere/settings/local.py.j2\u001b[0m\n\u001b[33mUndeclared variables found in …
```
=> Add callback plugin for human readable error output

README.md, requirements.txt
This fix makes a clank install more likely to succeed. You no longer need the latest virtualenv/pip.
The reason we had to update the virtualenv is to install a later version of setuptools which ansible (silently) required. This is a bug in ansible. It is documented in the requirements.txt.
=> Remove unnecessary install step

roles/install-dependencies/vars/Ubuntu.yml
The PostgreSQL project managed an Apt Repository [1], this will include
it and make new versions of the database available to the current
distro version, 14.04.3.
Thank you to Connor Osborn for refactoring this role to use lists.
[1] https://www.postgresql.org/download/linux/ubuntu/
=> Add official PostgreSQL Apt Repository

callback_plugins/human_log.py, dist_files/variables.yml.dist
In some situations, the logic of `_format_output(output)` will allow a non-string to make it down to Line 81. When? Will, if output is a `bool`, then you encounter the situation described in #90. 
Now, `_format_output` always returns a `str` and there will always be a `.replace` method available - but the formatting will not affect the overall result (just *no* _more_ `[WARNING]`).
=> Changed `_format_output()` to always return a str

playbooks/utils/upgrade_postgres.yml, roles/app-backup-postgres/README.md, roles/app-backup-postgres/defaults/main.yml, roles/app-backup-postgres/tasks/main.yml
Addresses Issue #83
This is the first _utility_ playbook defined within Clank. It does not
rely on any of the variables from the various Atmosphere build-env
files used to describe a given installation environment.
It will halt if you have not provided the two require variables:
- `pg_version` (the target to upgrade the server to)
- `pg_version_old` (the existing installation)
Optionally, you can pass a list of database to apply post-install
actions and generate "database-specific" backups:
```
$ clank # ansible-playbook playbooks/utils/upgrade_postgres.yml \
--flush-cache -c local -i "localhost," \
-e "{pg_version: '9.5',  pg_version_old: '9.3', database_names: ['atmosphere', 'troposphere']}"
```
Thank you Snehal Parmar for this outline provided on [DBA Stack …
=> Added playbook to upgrade to new Postgres

playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml, roles/config-nginx-uwsgi/tasks/main.yml, roles/setup-ssl/defaults/main.yml, roles/setup-ssl/tasks/main.yml
To specific verify and test this, you can use the _build-env_ from our local vagrant development environments and do a full, end-to-end `./clank.py` deploy. Then, using `nginx -t` to perform a configuration test. 
---
If you wanted to cut the activities associated with the issue, you might simulate a full `deploy_stack.yml` run by calling the roles in this order:
```
ansible-playbook "/opt/dev/clank/playbooks/deploy_stack.yml" \
--flush-cache -c local -e "@/vagrant/clank_init/build_env/variables.yml@local" \
-i "localhost," --tags "ssl" 
ansible-playbook "/opt/dev/clank/playbooks/deploy_stack.yml" \
--flush-cache -c local -e "@/vagrant/clank_init/build_env/variables.yml@local" \
-i "localhost," --tags "nginx-uwsgi" 
```
> *Note*: the reason I am using the raw playbook call is because …
=> Added conditional combined certification generation 

group_vars/novnc_proxy, playbooks/utils/README.md, playbooks/utils/install_novnc_auth.yml
This pull request defines a utility playbook to be install an optional component to enhance functionality of Atmosphere. The component is a [transparent authentication proxy using Nginx](https://github.com/cyverse/nginx_novnc_auth) to allow community members access to [noVNC](https://kanaka.github.io/noVNC/) running on an instance within the Atmosphere Cloud ☁️ . 
- a valid "build_env" variables.yml for Atmosphere (described in Clank [README.md](https://github.com/iPlantCollaborativeOpenSource/clank#list-of-files-needed-before-hand); examples in [dist_files](https://github.com/iPlantCollaborativeOpenSource/clank/blob/master/dist_files/variables.yml.dist))
- `hosts` including `[novnc_proxy]` group
```
ansible-playbook playbooks/utils/install_novnc_auth.yml \
-i hosts -e …
```
=> Defines playbook for install/config of `nginx_novnc_auth` within Atmosphere

roles/app-load-data-postgres/tasks/main.yml
The removal of `roles/app-load-data-postgres/vars/` in #113 causes the first task in `roles/app-load-data-postgres/tasks/main.yml` to fail to find a file to _include_ via `include_vars: ... with_first_found` (since there is *nothing* found).
The task I'm referring to is the pattern of "gather os specific" variaables
```
- name: gather os specific variables
include_vars: "{{ item }}"
with_first_found:
- "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
- "{{ ansible_distribution }}.yml"
- "{{ ansible_os_family }}.yml"
- "defaults.yml"
tags: vars
```
The *symptom* of this appears like the following:
```
TASK [app-config-postgres : debug] *********************************************
skipping: [localhost]
TASK [app-load-data-postgres : gather os specific variables] …
```
=> Fix failure when `with_first_found` finds nothing to `include_vars`

roles/app-config-logging/tasks/main.yml, roles/app-config-logging/vars/main.yml, roles/app-load-data-postgres/tasks/main.yml, roles/setup-postgres/vars/main.yml
The update to Ansible >2.0 meant [variable precedence](http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) changed and the
previous approach (plus the parameterization of roles) created some
unexpected "clobbering" (or, clearing - resets of variable values).
This removes the last few definitions.
*Note:* several `vars/main.yml` were left in place to avoid *breaking* :x: any "gather os-specific" variable task(s)
=> Removed remaining variable definitions

playbooks/deploy_stack.yml, playbooks/prepare_host.yml, requirements.yml, roles/distro-update/.travis.yml, roles/distro-update/README.md, roles/distro-update/license.md, roles/distro-update/meta/.galaxy_install_info, roles/distro-update/meta/main.yml, roles/distro-update/tasks/main.yml, roles/distro-update/tests/inventory, roles/distro-update/tests/test.yml
As part of deploying Atmosphere(1), we should ensure that distro-provided packages are up-to-date, especially for security updates. Here, I have added the new [CyVerse-Ansible/distro-update](https://github.com/CyVerse-Ansible/ansible-distro-update) role to perform this, as Clank's first action. I have tested and confirmed that it works in my atmo-local environment.
=> Running distro updates before deploying stack

playbooks/utils/backup_db.yml, playbooks/utils/backup_files.yml, playbooks/utils/perform_backup.yml, roles/app-backup-files/README.md, roles/app-backup-files/defaults/main.yml, roles/app-backup-files/tasks/main.yml
This PR is to hopefully eliminate the tedious deployment day task of backing up tedious files. Specifically I want to remove these steps from deployment day:
```
cd /root/atmo_backups/date +%Y_%m_%d`
cp /opt/dev/atmosphere/variables.ini .
cp /opt/dev/atmosphere/atmosphere/settings/local.py .
cp /opt/dev/atmosphere/atmosphere/settings/secrets.py .
cp /opt/dev/troposphere/variables.ini .
cp /opt/dev/troposphere/package.json .
cp /opt/dev/troposphere/troposphere/settings/local.py .
cp /etc/nginx/sites-enabled/* .
cp /etc/nginx/locations/* .
cp /etc/uwsgi/apps-enabled/* .
cp /etc/default/celeryd .
```
The role requires two variables. The `BACKUP_PATH` variable defines a location of where to save the backups to, containing a dir named after a date stamp.
```
BACKUP_PATH: /root/atmo_backups
``` …
=> Create a role to automate the backing up of important files

playbooks/utils/create_release_virtualenvs.yml
This util playbook is to be run before release deployment. It creates python virtualenvs that are named based on the release abbreviations. The playbook requires a variable to be passed in, e.g. `-e RELEASE_INITIALS=rr`.
This should save us a few more minutes on deployment day.
=> Add util playbook to create release virtualenvs

.travis.yml, roles/install-dependencies/vars/Ubuntu.yml
Steps were made to allow travis to deploy clank while installing a 9.6 cluster.
P.S. I recommend a squashing of my commits.
=> Have travis c.i. be able to setup a 9.6 postgresql cluster

group_vars/atmosphere, group_vars/common, group_vars/troposphere
To avoid compatibility errors, also allow variables files to define either STAFF_LIST_USERNAMES (old) or MAINTENANCE_EXEMPT_USERNAMES to fill out the required variables.
Atmosphere PR: https://github.com/iPlantCollaborativeOpenSource/atmosphere/pull/207
Troposphere PR: https://github.com/iPlantCollaborativeOpenSource/troposphere/pull/475
Clank PR: https://github.com/iPlantCollaborativeOpenSource/clank/pull/130
=> Add required variables for MAINTENANCE_EXEMPT_USERNAMES

ansible.cfg, dist_files/variables.yml.dist, group_vars/common, playbooks/prepare_host.yml, playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml, playbooks/utils/install_novnc_auth.yml, roles/clone-repo/tasks/main.yml, roles/install-dependencies/tasks/main.yml
The goal is to reduce the tweak/rebuild/test cycle time for developers using Clank with the [atmo-local](https://gitlab.cyverse.org/atmosphere/atmo-local) environment. Basically, you set `faster_dev_rebuild` to `true` when you want your development environment to rebuild much more quickly, at the expense of maybe getting slightly older dependencies.
Benchmarking on my laptop, the first run (with no existing caches) takes about 26 minutes, but after the caches are populated, subsequent complete rebuilds (destroying and re-creating the Vagrant VM) take about 10 minutes.
When `faster_dev_rebuild` is set to true, Clank skips the full update of all distro packages and uses the local PIP cache for installing Python dependencies. When used with …
=> Faster dev environment rebuilds

roles/app-pip-install-requirements/tasks/main.yml
There has been an odd bug popping up that has pip not receiving certain arguments well. [Builds](https://travis-ci.org/iPlantCollaborativeOpenSource/clank/builds/174064627) were also failing as pip was taking an incredible amount of time to complete. 
modified:   roles/app-pip-install-requirements/tasks/main.yml
=> Have pip update itself

group_vars/troposphere
Update group_vars file regarding troposphere file. As we move repos from iplantcollaborativeorg, we have to update our vars.
=> Fix troposphere git url

.travis.yml, group_vars/atmosphere
The [`DEBUG` and `SEND_EMAILS` variables](https://github.com/cyverse/atmosphere/blob/master/atmosphere/settings/local.py.j2#L14-L16) defined for `atmosphere/settings.local.py` are set based on the `DJANGO_DEBUG` variable. Unfortunately, this variables within Clank `group_vars/atmosphere` is not defined in a way that makes it easily overridden in a "build-environment" file (see commit 4f9343d for more discussion).
This pull request defined `DJANGO_DEBUG` within `[local.py]` based on the `DEBUG` variable in `group_vars/atmosphere` placed with "override" session:
```
###############################
#5. Overrides for Clank Execution
###############################
faster_dev_rebuild: true
DEBUG: False
```
<details>
I demonstrate the variable being set within a vagrant environment.
Based on …
=> Allow override of `DJANGO_DEBUG` variable

playbooks/utils/backup_db.yml
The backup_db playbook had hard-coded database names (`atmo-prod` and `troposphere`) that do not match the default database names that Clank creates if you do not specify database names (`atmosphere` and `troposphere`). This PR removes those hard-coded names, fixing an error condition that occurs when you try to run the backup_db playbook against an Atmosphere that was deployed with Clank's defaults. Instead, all databases should be backed up.
=> Don't explicitly define database names in backup_db playbook which conflict with default database names elsewhere in Clank

dist_files/variables.yml.dist
As part of the process of reviewing atmosphere/troposphere, we decided to include additional documentation about why and when to use keystone auth.
=> Update the dist-file to include instructions on enable Keystone auth

group_vars/atmosphere, group_vars/troposphere, roles/setup-postgres/tasks/main.yml
Our django apps don't talk to the database via unix sockets.
This is what _used_ to be our `pg_hba.conf`.
```
local   all              all                       peer  
...                 
local   all              atmo_app                  md5
```
The issue is that the lower line (which we add) is overriden by the above line, because the above is more restrictive. It states:
>On domain sockets, for all databases and all users require auth via unix login credentials
This pr ensures the proper ordering. Because our apps could not login via unix auth, they resorted to tcp over the loopback interface. Now they use domain sockets.
This is significant, because engaging the network stack adds about 33%
overhead compared to domain sockets.
http://stackoverflow.com/a/12101626/1213041
Finally, in …
=> Fix incorrect permissions for database user, allow connections on domain sockets

.travis.yml, playbooks/deploy_stack.yml, playbooks/post_deployment.yml, roles/app-alter-kernel-for-imaging/tasks/main.yml, roles/atmosphere-include-startup/README.md, roles/atmosphere-include-startup/license.md, roles/atmosphere-include-startup/tasks/main.yml
Summary:
- Include a new playbook to handle post_deployment steps
- include a new post deployment step: add atmosphere to startup (via rc.local)
Tests:
=> Include atmosphere in the Linux Startup process (via rc.local)

group_vars/troposphere, playbooks/setup_troposphere.yml, roles/install-theme/tasks/main.yml
_This is failing travis because it is dependent on [PR 560](https://github.com/cyverse/troposphere/pull/560). Test locally with [this branch](https://github.com/Tharon-C/troposphere/tree/ATMO-1734-cy-ui-integration)_
This PR is part of ATMO-1734 integrating CY-UI and MUI into troposphere. These libraries use a configuration object for theming over the current CSS method. Now theme colors are set as vars and a custom images folder can be provided to change the logos, CTA images, and favicon. 
- Add theme group vars
- Create role for symlinking images folder into troposphere theme. 
- Add role to tropo playbook and use theme tag
=> Problem: add theme-specific variable population

README.md, dist_files/variables.yml.dist
This adds theme documentation in variables.yml.dist
Includes what the variables are, how to use them, and uses Jetstream colors as commented out example.
=> Problem: Theme documentation is missing

group_vars/troposphere
Solution: Added defaults for:
- EXTERNAL_ALLOCATION
- ALLOCATION_UNIT_NAME
- ALLOCATION_UNIT_ABBREV
This PR is dependent on: https://github.com/cyverse/atmosphere/pull/340
This change is due to: https://github.com/cyverse/troposphere/pull/565/commits/0e12b6d37687a89cdadc561e7289cb4d5a2a5a18
=> Problem: Missing defaults for allocation group vars

roles/tls-cert/README.md, roles/tls-cert/meta/.galaxy_install_info, roles/tls-cert/tasks/deploy-provided.yml
The latest fixes the tls cert mismatch:
CyVerse-Ansible/ansible-tls-cert @d455f35:
> Create a new full chain cert when parts of the chain change
>
> Problem:
> When users were re-running clank, they were experiencing certificate mismatch
> errors, because our ansible was not recreating the full chain. It wasn't
> recreating it because the module performing the concatenation only
> checked if the full chain file previously existed not whether it should be
> recreated.
>
> Solution:
> Take a stroke from make, when ever the timestamps of the inputs are newer than
>     the output, regenerate the output.
>
=> Pull in latest ansible galaxy tls-cert role

README.md, clank.py, playbooks/utils/README.md
Problem: clank.py hardcodes utilities into the command options
Solution: allow a playbook to be passed to clank
I have a utility in the works which creates a certificate/ca and I wanted the experience to be better when adding support for another utility.
=> Add support for running util playbooks via --playbook

playbooks/utils/README.md, playbooks/utils/create_ca_and_cert.yml, playbooks/utils/create_ca_and_cert_README.md, roles/tls-ca-sign-csr/README.md, roles/tls-ca-sign-csr/defaults/main.yml, roles/tls-ca-sign-csr/tasks/main.yml, roles/tls-ca-sign-csr/templates/openssl-ca.cnf.j2, roles/tls-cert/README.md, roles/tls-cert/meta/.galaxy_install_info, roles/tls-cert/tasks/deploy-provided.yml, roles/tls-create-ca/README.md, roles/tls-create-ca/defaults/main.yml, roles/tls-create-ca/tasks/main.yml, roles/tls-create-ca/templates/openssl-ca.cnf.j2, roles/tls-create-csr/README.md, roles/tls-create-csr/defaults/main.yml, roles/tls-create-csr/tasks/main.yml, roles/tls-create-csr/templates/openssl-server.cnf.j2
This PR includes a utility playbook to create a certificate authority (CA) and certificates signed by said authority. Here is the associated [documenation](https://github.com/cdosborn/clank/blob/6dcec30b23013f83a26aa77754085020c2867849/playbooks/utils/create_ca_and_cert_README.md).
I think there are several reasons why this work offers improvements over our current solution:
- It works for developers outside our organization
- There is no sharing of certs and keys
- The certs don't expire (mostly true)
This pr depends on #175. That should be merged first.
=> Add utility to self issue certs for local dev

playbooks/deploy_atmosphere.yml, playbooks/deploy_troposphere.yml, playbooks/utils/create_ca_and_cert.yml, roles/tls-cert/README.md, roles/tls-cert/meta/.galaxy_install_info, roles/tls-cert/tasks/deploy-selfsigned.yml, roles/tls-cert/templates/openssl-req.cnf.j2
The description/problem can be found here https://github.com/CyVerse-Ansible/ansible-tls-cert/pull/5. 
The second commit fixes the issue where certs never get **re**generated.
=> Fix self-signed certificate failures in Chrome (v58)

.travis.yml, playbooks/deploy_atmosphere.yml, playbooks/deploy_stack.yml
Problem: broken clank build
Solution: Don't use the brand new buggy trusty image released yesterday
Yesterday travis rolled out a new trusty image that was broken. Ansible was
failing to add repositories because the trusty image had a broken repository
in its list.
https://blog.travis-ci.com/2017-06-21-trusty-updates-2017-Q2-launch
=> Use older trusty box that has working apt repos

playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml
Remove redundant install of requirements.
`pip install requirements.txt dev_requirements.txt` is redundant because dev_requirements.txt contains requirements.txt. 
depends on #187 (already merged)
depends on https://github.com/cyverse/troposphere/pull/629 (already merged in z-z)
depends on https://github.com/cyverse/atmosphere/pull/399
**Note:**
I think travis builds clank against tropo/atmo master, so we need the above prs to not only go into z-z but also into master.
=> Install only dev deps in clank

playbooks/utils/README.md
`upgrage_postgres.yml` -> `upgrade_postgres.yml`
=> Fixed typo in utils README.md

group_vars/atmosphere, group_vars/troposphere
Different environment will need to tune the number of uWSGI processes for handling requests. 
This work makes `NUM_PROCESSES` a variable within the `uwsgi.ini` variables section, and allows for _override_ variables to be defined for Atmosphere and Troposphere.
These variables can be overridden within a `variables.yml` build environment file:
- `atmosphere_uwsgi_processes`
- `troposphere_uwsgi_processes`
This depends on `NUM_PROCESSES` being introduced within Atmosphere and Troposphere as well.:
- [cyverse/atmosphere pull request 401](https://github.com/cyverse/atmosphere/pull/401)
- [cyverse/troposphere pull request 640](https://github.com/cyverse/troposphere/pull/640)
=> Problem: number of uWSGI processes not configurable

.travis.yml
When travis runs clank, it always builds the master branches of atmo/tropo which is often not what you want. 
Allow any travis user to set variables which determine the branches/repos for clank to build.
<br/>
1. Define variables like so in your travis respository settings
2. Profit 🎉
=> Allow travis to override which atmo/tropo repos clank builds

roles/setup-webserver-user-group/defaults/main.yml, roles/setup-webserver-user-group/tasks/main.yml
Otherwise you get errors like these:
```
IOError: [Errno 13] Permission denied: '/var/tmp/django_cache/96b2eeef9dbbd9d34340463b78cbd10b.djcache'
```
Solution: Set the correct permissions. Also create this directory if it
doesn't exist.
=> Problem: Django cache directory should be owned by www-data

clank.py
Solution: Dramatically speed-up the time it takes to run Clank by
skipping one-time build steps
Signed-off-by: Julian Pistorius <julian@julianpistorius.com>
=> Problem: Clank has slow steps which can be skipped in dev

group_vars/troposphere
Solution: Include `BUILD_TYPE` as a variable for troposphere, piggy-backing off of `INSTALLATION_TYPE`
=> Problem: Troposphere does not know if environment is production or development.

group_vars/troposphere
The Allocation Unit name is already pluralized, inline, where used. We can re-evaluate this when an Internationalization (i18n) effort is done.
=> Problem: allocation units appear with extra 's' at end

playbooks/setup_atmosphere.yml, roles/app-pip-install-requirements/tasks/main.yml
As of Ansible 2.3, conditonal statements that use the full Jinja2 templating syntax with filters cause errors. The full variable syntax is not required in Ansible, **only** in the `when:` lines, so removing the `{{ }}` fixed the error but maintains the functionality of having defaults.
[ATMO-1894](https://pods.iplantcollaborative.org/jira/browse/ATMO-1894)
Example of error:
```
TASK [app-pip-install-requirements : pip install requirements] *************************************
Wednesday 07 June 2017  13:22:49 -0700 (0:00:01.298)       0:00:38.084 ********
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}.
Found: not "{{ USE_PIP_TOOLS_SYNC | default(False) }}"
```
=> Remove jinja syntax from conditionals

roles/app-load-data-postgres/tasks/main.yml
The line including `var={{ ... }}` is not valid syntax. These debug statements
really shouldn't exist, just noise.
The line including `var={{ ... }}` is not valid syntax.
This fixes an error that is only triggered if you set `DEBUG_OR_TEST_ROLE: true`
=> Cleanup error throwing debug

CHANGELOG.md, dist_files/variables.yml.dist, group_vars/atmosphere, group_vars/common, group_vars/troposphere, playbooks/deploy_atmosphere.yml, playbooks/deploy_troposphere.yml, playbooks/utils/create_ca_and_cert_README.md, roles/tls-cert/.travis.yml, roles/tls-cert/README.md, roles/tls-cert/defaults/main.yml, roles/tls-cert/meta/.galaxy_install_info, roles/tls-cert/meta/main.yml, roles/tls-cert/tasks/deploy-letsencrypt.yml, roles/tls-cert/tasks/deploy-provided.yml, roles/tls-cert/tasks/deploy-selfsigned.yml, roles/tls-cert/tasks/get-cert-cn.yml, roles/tls-cert/tasks/main.yml, roles/tls-cert/tasks/register-file-paths.yml, roles/tls-cert/templates/openssl-req.cnf.j2
Integrated new [ansible-tls-cert](https://github.com/CyVerse-Ansible/ansible-tls-cert) into Clank. To deploy yourself an atmosphere(1) with a certificate from Let's Encrypt, simply set the following in your `variables.yml`:
```
TLS_LETSENCRYPT_ENABLE: true
TLS_LETSENCRYPT_EMAIL: "dont@spam.me"
```
```
TLS_LETSENCRYPT_ENABLE: true
TLS_LETSENCRYPT_EMAIL: "{{ ADMINS_EMAIL_TUPLE[0][1] }}"    
```
=> Let's Encrypt support

roles/app-install-instance-deploy-automation/tasks/main.yml
Problem: Clank was installing the templated file on the wrong machine
Solution: Install templated file onto the target host, not where ansible is being deployed from
Fixes: https://github.com/cyverse/clank/issues/223
=> Install templated file against the target host

roles/setup-celery/templates/celeryd.j2
Previoulsy we were deploying against vms with the www-data user. There are several hitches required to make this work. We would need www-data have permissions on ssh keys and make sure that that user has an ssh config in their home directory, and make sure that they have a home directory with the right permissions.
It's not really obvious that there is any benefit to running ansible deploys as non-root. Its less secure since every web request would be running with permissions enabling them to ssh into vms.
This change makes ansible deploys left to a root worker. I tested and verified that all tasks which use ssh are in the proper queue `ssh_deploy`.
Include snippets of code to help reviewers test your code!
=> Run instance-deploy celery worker as root user

roles/atmosphere-include-startup/files/atmosphere
Problem: atmosphere init script "status" command didn't produce anything useful
Solution: print the output of each sub-services' status command
Here's the new output:
```
$ service atmosphere status
service flower status
flower is stopped
service celerybeat status
celerybeat is stopped
service uwsgi status atmosphere
* uwsgi is running
service uwsgi status troposphere
* uwsgi is running
service nginx status
nginx start/running, process 16939
service celeryd status
celeryd is stopped
```
=> Make atmosphere status print status of each sub command

.travis.yml, requirements.txt
Problem: out of date setuptools causes travis build failure
Solution: install latest setuptools by installing after virtualenv is created
**Note:** travis is still broken, but it's failing because of a separate issue with postgres see (https://github.com/cyverse/clank/pull/239)
=> Fix travis crypto dep error

roles/setup-celery/templates/celeryd.j2
Problem: service celeryd start throws exception when CELERYD_PRODUCTION_WORKER_SETUP=false
Solution: call celery cli differently
The celeryd cli does not support indexing by worker name, when there is only
one worker so "-c:workername-with-hyphen 3"  would result in:
```
ValueError: invalid literal for int() with base 10: 'workername'
```
Seems like a celeryd bug, multi should support 1 or more workers..
Please describe your pull request. If it fixes a bug or resolves a feature
request, be sure to link to that issue. When linking to an issue, please use
`refs #...` in the description of the pull request.
Include snippets of code to help reviewers test your code!
=> Fix parse error for celeryd init script

group_vars/common, playbooks/deploy_atmosphere.yml, playbooks/deploy_troposphere.yml, playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml, roles/app-config-postgres/tasks/main.yml, roles/install-dependencies/vars/Ubuntu.yml, roles/setup-postgres/README.md, roles/setup-postgres/defaults/main.yml, roles/setup-postgres/handlers/main.yml, roles/setup-postgres/tasks/main.yml
This pr depends on #238, which should be merged first.
This pr allows clank to install either postgres 9.6 or 10. The default is 9.6.
```
ansible-playbook -e @$ENV_FILE playbooks/deploy_stack.yml  -e pg_version=10 --tags database
ansible-playbook -e @$ENV_FILE playbooks/deploy_stack.yml  -e pg_version=9.6 --tags database
```
The above commands don't ensure that anything is loaded into the db, so if you're going from 9.6 -> 10, you should do an entire clank run with:
```
ATMO_DATA:
LOAD_DATABASE: True
SQL_DUMP_FILE: /path/to/sql/dump
```
=> Postgres 10

roles/build-install-troposphere-ui-assets/tasks/main.yml
**Note:** this depends on #239, which should be merged first
Problem: travis times out during npm install (see this [build](https://travis-ci.org/cyverse/clank/builds/301580614#L2780-L2791))
Solution: during a root npm install, explicitly allow pkgs' build scripts to build as root by using (--unsafe-perm), this fixed an issue where node-gyp had the wrong permissions and tried indefinitely
When you npm install as root, npm tries to protect you and runs build scripts as a non-privileged user (otherwise you're allowing any npm package root access on your machine). This almost always fails, because the source code is typically owned by the root user, so this unprivileged build will fail.
=> Fix travis err during npm install

roles/atmosphere-include-startup/files/atmosphere
Services like celery and celerybeat will throw an exit code of 1 if they have already been started/stopped.
Atmosphere service previously bailed out on non-zero exit codes.
Instead, show the output of the individual calls being made, and print a warning (but continue to other services)
if a non-zero exit code is found.
=> Problem: atmosphere startup script is not idempotent

roles/setup-celery/templates/celeryd.j2
when `CELERYD_PRODUCTION_WORKER_SETUP : false`, instance launch wouldn't work
fix the celeryd configuration, so that tasks get routed to correct queues
celery_periodic and fast-deploy were typos in the queue names, so tasks were being put in queues that had no workers working through them
only affects dev environments
=> Fix incorrect queue names

dist_files/variables.yml.dist, group_vars/atmosphere, group_vars/common, playbooks/prepare_host.yml, playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml
This is part of the effort outlined to make clank more reasonable to configure. Don't have variables with misleading names, and don't have variables that set other vars. 
So rather than have `DEVELOPMENT: True` have narrow variables that are configured properly for in a development variables.yml. This makes configuration way easier to reason about.
This is part of https://pods.iplantcollaborative.org/jira/browse/ATMO-1993
TODO:
=> Replace overly broad vars

roles/setup-celery/templates/celerybeat.j2
Script restart would not actually stop the service
Actually pass the $pid to kill
=> Fix celerybeat failing to stop process

roles/clone-repo/tasks/main.yml
When there are local modifications clone-repo fails, and doesn't mention where they are
```
TASK [clone-repo : clone git repo with branched defined]
...
fatal: "Local modifications exist in repository (force=no)
```
```
TASK [clone-repo : Clone git repo https://github.com/CyVerse/atmosphere-ansible.git with branch master]
...
fatal: "Local modifications exist in repository (force=no)
```
To test:
```
echo hi >> /opt/dev/troposphere/README.md
ansible-playbook -e @$ENV_FILE playbooks/deploy_troposphere.yml --tags clone-repo
```
=> Make clone-repo more verbose

roles/configure-nginx/templates/tropo-uwsgi.conf.j2
For the location that uses the authentication location, the request were not coming in with the necessary uWSGI parameters. 
```
Message
KeyError: u'REQUEST_METHOD'
```
This happens within the WSGI callable when trying to index into the the `environ`. There is not key for `'REQUEST_METHOD'`. This will appear in the outside world as a `502 Bad Gateway` within nginx (you can see this in error.log).
The work includes the `uwsgi_params` for the auth callback, and all is well.
=> Problem: CAS callback needs uWSGI request params

roles/setup-celery/templates/celeryd.j2
Problem:
The celeryd init script force kills after a few seconds, which is not ideal for production
Solution:
Use the builtin celeryd restart, which doesn't force kill, until it is run a second time.
This just copies the start command and replaces the celeryd argument "start" with "multi". There is a lot of baggage required to run each command. Part of the reason is that an init script gets loaded once, and every service restart etc, continues to use the same environment. So its wise to not source a virtualenv, or export a variable like `C_FORCE_ROOT`.
=> Prefer builtin celeryd restart over custom restart

README.md, playbooks/setup_atmosphere.yml
This PR just adds the `kernel` tag to the `setup_atmosphere.yml` playbook's use of role `app-alter-kernel-for-imaging` so I can skip this role in Docker. I also added some info to the README next to the info about other tags.
Docker does not allow kernel modification, so I have to skip this role in my Docker build, but it is not maintainable to use `sed -i '5,6d' playbooks/setup_atmosphere.yml` to delete the lines.
=> Add 'kernel' tag to 'app-alter-kernel-for-imaging' role

dist_files/variables.yml.dist, group_vars/atmosphere, group_vars/troposphere, playbooks/deploy_stack.yml, roles/configure-nginx/README.md, roles/configure-nginx/defaults/main.yml, roles/configure-nginx/templates/site.conf.j2
Allows an atmosphere(1) server to answer on multiple hostnames so that we can do rolling deployments to a fresh instance and fast cutovers during a short maintenance period.
Co-depends on [atmosphere #602](https://github.com/cyverse/atmosphere/pull/602) and [troposphere #771](https://github.com/cyverse/troposphere/pull/771).
=> WIP: Supporting multiple hostnames for Atmosphere(1) server

CHANGELOG.md, playbooks/utils/backup_db.yml, roles/app-backup-postgres/README.md, roles/app-backup-postgres/defaults/main.yml, roles/app-backup-postgres/tasks/main.yml
Database backups were made in a separate folder from the configuration backups.
Change the default backup folder, and fix postrgresql permission limitations
I think this is just a small improvement, along with an echo of where the backups are made, which will be helpful with the new deploy process, where we will be making backups on prod, and then installing those on the staging.
=> Create backups in a single directory

CHANGELOG.md, roles/sanitary-sql-access/templates/sanitize-dump.sh.j2
Fixing bugs and quirks so that the `sanitary-sql-access` role will work on all production deployments.
=> Sanitary SQL Access tweaks for Jetstream Cloud

.travis.yml, CHANGELOG.md, group_vars/atmosphere
Replace Subspace by using Ansible's PlaybookCLI to deploy instances.
In order to be compatible with the related branches of Atmoshere and Atmosphere-Ansible, names of variables in `group_vars` were changed to replace `SUBSPACE` with `ANSIBLE` since Subspace is no longer used.
Related PRs:
- [Atmosphere PR #631](https://github.com/cyverse/atmosphere/pull/631)
- [Atmosphere-Ansible PR #154](https://github.com/cyverse/atmosphere-ansible/pull/154)
=> ATMO-2149: Atmosphere deploy without Subspace

CHANGELOG.md, roles/app-setup-ssh-keys/tasks/main.yml
Ansible was not using the deploy key found in the secrets repo
When checking if the deployer has a key to copy over, check locally, since the secrets repo is local
=> Correctly find atmo deploy key in local secrets repo

CHANGELOG.md, group_vars/common, playbooks/deploy_stack.yml, roles/configure-nginx/templates/site.conf.j2
Nginx incorrectly redirects users from http://<atmo server> to https://https://<atmo server>
The template assumed that SERVER_URL did NOT include the protocol prefix
(https://). Correct the template to assume that SERVER_URL includes the protocol
=> Fix nginx http to https redirect

CHANGELOG.md, group_vars/atmosphere
1) Make SEND_EMAILS its own variable
SEND_EMAILS used to be derived from another variables, which makes configuration more difficult to reason about.
2) Change DJANGO_DEBUG name and default
Both troposphere and atmosphere have a global debug, they now have the same name. They now both default to False (used to have different defaults).
See https://github.com/cyverse/atmosphere/pull/649
=> Simplify vars send emails and debug

CHANGELOG.md, playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml, roles/app-load-data-postgres/README.md, roles/app-load-data-postgres/tasks/main.yml
- Troposphere database was not being deleted, because LOAD_DATABASE was not being passed
- Atmophsere database was not being deleted, because LOAD_DATABASE was not being passed properly
- Pass variables properly
- Refactor role to remove variable which turns role off/on and use when clauses
with role instead to selectively include it
=> Fix database loading

CHANGELOG.md, group_vars/atmosphere
Solution: Add `ALLOCATION_OVERRIDES_NEVER_ENFORCE` and
`ALLOCATION_OVERRIDES_ALWAYS_ENFORCE` into group_vars/atmosphere
=> Problem: Enforcement overrides not configurable by Clank

CHANGELOG.md, group_vars/atmosphere, group_vars/troposphere, playbooks/setup_atmosphere.yml, playbooks/setup_troposphere.yml
Prefer flat variables for database loading
```
ATMO_DATA:
LOAD_DATABASE: false
SQL_DUMP_FILE:
TROPO_DATA:
LOAD_DATABASE: false
SQL_DUMP_FILE:
```
```
ATMO_LOAD_DATABASE: false
ATMO_SQL_DUMP_FILE:
TROPO_LOAD_DATABASE: false
TROPO_SQL_DUMP_FILE:
```
=> Flatten nested ATMO_DATA and TROPO_DATA variables

CHANGELOG.md, playbooks/prepare_host.yml, roles/install-dependencies/tasks/main.yml, roles/install-dependencies/vars/Ubuntu.yml
Atmosphere emails were not being sent
Install and start a local smtp server
Atmosphere depends on a local smtp server to send mail. See the Django
EMAIL_HOST variable[1].
[1] https://docs.djangoproject.com/en/2.1/ref/settings/#email-host
I tested that this playbook installs an smtp server and ensures its running
=> Install smtp server to send outgoing emails

CHANGELOG.md, group_vars/atmosphere
Remove variables that were relevant to old allocation system. Depends on https://github.com/cyverse/atmosphere/pull/656.
=> Remove unused variables DEFAULT_ALLOCATION_{THRESHOLD,DELTA}

CHANGELOG.md, group_vars/atmosphere, group_vars/troposphere
Remove traces of `USE_ALLOCATION_SOURCES`. This variable allowed us to transition from the old allocation system to the new one. We no longer use the old one and can remove all this variable's references.
=> Remove unused USE_ALLOCATION_SOURCE(S) variables

CHANGELOG.md, group_vars/atmosphere
`TACC_API_TIMEOUT` was replaced in favor of `TACC_READ_API_TIMEOUT` because it
only applied to GETs
Related: https://github.com/cyverse/atmosphere/pull/668
- This variable is not actually configurable, because ansible cannot template numbers
=> Rename TACC_API_TIMEOUT to TACC_READ_API_TIMEOUT
